name: todo_app_riverpod
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  smooth_page_indicator: ^1.1.0
  flutter_vector_icons: ^2.0.0
  pinput: ^3.0.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  hooks_riverpod: ^2.3.7
  flutter_hooks: ^0.20.0
  riverpod_annotation: ^2.1.1
  country_picker: ^2.0.20
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.5
  riverpod_lint: ^2.0.0
  custom_lint: ^0.5.1


flutter:

  uses-material-design: true
  assets: 
    - assets/images/
